name: taxi_lakehouse
version: "1.0.0"
config-version: 2

profile: taxi_lakehouse

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]

clean-targets:
  - target
  - dbt_packages

models:
  taxi_lakehouse:
    enriched:
      +materialized: table
      +tags:
        - enriched
